apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: linkerd
  name: linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linkerd
    spec:
      containers:
      - image: linkerd
        name: linkerd
        resources: {}
status: {}
